# Generated by Django 3.0 on 2019-12-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('initiative', '0001_initial'), ('initiative', '0002_initiative_date'), ('initiative', '0003_initiative_visual'), ('initiative', '0004_auto_20191205_1615'), ('initiative', '0005_remove_initiative_visual')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
