# Generated by Django 2.2.8 on 2019-12-05 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
