# Generated by Django 3.0 on 2019-12-12 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='timeline',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
