# Generated by Django 3.0 on 2019-12-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial_squashed_0005_remove_initiative_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
