# Generated by Django 2.2.8 on 2019-12-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_initiative_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='visual',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
