# Generated by Django 3.0 on 2019-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_initiative_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='timeline',
            field=models.TextField(blank=True),
        ),
    ]
