# Generated by Django 3.0 on 2019-12-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_auto_20191213_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative.Initiative'),
        ),
    ]
