# Generated by Django 2.2.8 on 2019-12-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_initiative_visual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='visual',
            field=models.URLField(verbose_name=''),
        ),
    ]
