# Generated by Django 2.2.8 on 2019-12-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0004_auto_20191205_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='visual',
        ),
    ]
