# Generated by Django 3.0 on 2019-12-06 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoutouts_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoutouts_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
