# Generated by Django 3.0 on 2019-12-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoutouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoutout',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoutouts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoutout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoutouts_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
