# Generated by Django 3.0 on 2019-12-09 18:59

from django.db import migrations, models
import reflections.models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='date',
            field=models.DateField(default=reflections.models.today_utc),
        ),
    ]
