# Generated by Django 2.2.7 on 2019-11-25 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import magic_links.models
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default=secrets.token_urlsafe)),
                ('expires_at', models.DateTimeField(default=magic_links.models.thirty_days_from_now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
