# Generated by Django 3.0 on 2019-12-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoutouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField()),
                ('shoutout', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
