# Generated by Django 3.0 on 2019-12-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic_links', '0002_shoutouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoutouts',
        ),
    ]
