# Generated by Django 2.2.7 on 2019-12-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileage_tracker', '0002_auto_20191206_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivetowork',
            name='in_put',
        ),
    ]
