# Generated by Django 3.0 on 2019-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_checkin_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
