# Generated by Django 3.0 on 2019-12-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_checkin_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.IntegerField(choices=[(1, 'Absent'), (2, 'Present'), (3, 'Tardy'), (4, 'Excused')], default=1),
        ),
    ]
